### ISSUE TITLE
plugin fails on netbox v3.1.1 

### ISSUE THREAD

**Issue by Dees7** [auroraresearchlab/netbox-dns#104]
Hello.
plugin doesn't work on version 3.1.1

```
<class 'django.urls.exceptions.NoReverseMatch'>
'netbox_dns' is not a registered namespace inside 'plugins'
Python version: 3.8.10
NetBox version: 3.1.1
```
And it fails on  manage.py migrate 

```
../venv/bin/python manage.py migrate 
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox-3.1.1/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/opt/netbox-3.1.1/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/netbox-3.1.1/venv/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/netbox-3.1.1/venv/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/opt/netbox-3.1.1/venv/lib/python3.8/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/opt/netbox-3.1.1/venv/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 75, in handle
    self.check(databases=[database])
  File "/opt/netbox-3.1.1/venv/lib/python3.8/site-packages/django/core/management/base.py", line 419, in check
    all_issues = checks.run_checks(
  File "/opt/netbox-3.1.1/venv/lib/python3.8/site-packages/django/core/checks/registry.py", line 76, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/opt/netbox-3.1.1/venv/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/opt/netbox-3.1.1/venv/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/opt/netbox-3.1.1/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 416, in check
    for pattern in self.url_patterns:
  File "/opt/netbox-3.1.1/venv/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/netbox-3.1.1/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 602, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/opt/netbox-3.1.1/venv/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/netbox-3.1.1/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 595, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/netbox-3.1.1/netbox/netbox/urls.py", line 9, in <module>
    from extras.plugins.urls import plugin_admin_patterns, plugin_patterns, plugin_api_patterns
  File "/opt/netbox-3.1.1/netbox/extras/plugins/urls.py", line 28, in <module>
    urlpatterns = import_object(f"{plugin_path}.urls.urlpatterns")
  File "/opt/netbox-3.1.1/netbox/extras/plugins/utils.py", line 31, in import_object
    spec.loader.exec_module(module)
  File "/opt/netbox-3.1.1/venv/lib/python3.8/site-packages/netbox_dns/urls.py", line 5, in <module>
    from .views import (
  File "/opt/netbox-3.1.1/venv/lib/python3.8/site-packages/netbox_dns/views.py", line 3, in <module>
    from netbox_dns.forms import (
  File "/opt/netbox-3.1.1/venv/lib/python3.8/site-packages/netbox_dns/forms.py", line 37, in <module>
    class ZoneForm(BootstrapMixin, CustomFieldModelForm):
  File "/opt/netbox-3.1.1/venv/lib/python3.8/site-packages/django/forms/models.py", line 226, in __new__
    new_class = super().__new__(mcs, name, bases, attrs)
  File "/opt/netbox-3.1.1/venv/lib/python3.8/site-packages/django/forms/forms.py", line 31, in __new__
    new_class = super().__new__(mcs, name, bases, attrs)
  File "/opt/netbox-3.1.1/venv/lib/python3.8/site-packages/django/forms/widgets.py", line 191, in __new__
    new_class = super().__new__(mcs, name, bases, attrs)
TypeError: Cannot create a consistent method resolution
order (MRO) for bases BootstrapMixin, CustomFieldModelForm
```

**Comment by peteeckel** [comment]
You installed the current version 0.6 from PyPi, correct? That version does not work with Netbox 3.1.x. See #89.

The current main branch has a working version, so if you can use that one it should (almost, there is PR #103 that is still required) work. Not sure when the next release will be pushed, though.

**Comment by Dees7** [comment]
Great! thanks.

**Comment by hatsat32** [comment]
I think this issue is fixed. Reopen if this still exists.
Closed!
