### ISSUE TITLE
NetBox version: 3.1.1 missing DB column

### ISSUE THREAD

**Issue by D1StrX** [auroraresearchlab/netbox-dns#108]
django.db.utils.ProgrammingError: column netbox_dns_zone.soa_serial_auto does not exist
```
<class 'django.db.utils.ProgrammingError'>

column netbox_dns_zone.soa_serial_auto does not exist
LINE 1: ...e"."soa_expire", "netbox_dns_zone"."soa_minimum", "netbox_dn...

Python version: 3.8.10
NetBox version: 3.1.1
```

**Comment by hatsat32** [comment]
Hi D1StrX

Are you sure you did run `manage.py migrate`? I checked migration files and column soa_serial_auto should be created when you run `migrate` command.

**Comment by D1StrX** [comment]
Doesn't work for me. Ill first try to figure out some other stuff. Closing this for now and get back if I get the issue again.

**Comment by D1StrX** [comment]
DB is from 3.0.10. And on 3.1.1 it doesn't nicely create/migrate the columns. 
Within the Python venv correct folder: ./manage.py migrate

Operations to perform:
  Apply all migrations: admin, auth, circuits, contenttypes, dcim, django_rq, extras, ipam, netbox_dns, sessions, social_django, taggit, tenancy, users, virtualization, wireless
Running migrations:
  Applying netbox_dns.0005_update_ns_records...Traceback (most recent call last):
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/models/query.py", line 581, in get_or_create
    return self.get(**kwargs), False
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
netbox_dns.models.DoesNotExist: Record matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 173, in __get__
    rel_obj = self.field.get_cached_value(instance)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/models/fields/mixins.py", line 15, in get_cached_value
    return instance._state.fields_cache[cache_name]
KeyError: 'zone'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column netbox_dns_zone.soa_serial_auto does not exist
LINE 1: ...e"."soa_expire", "netbox_dns_zone"."soa_minimum", "netbox_dn...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 244, in handle
    post_migrate_state = executor.migrate(
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/migrations/migration.py", line 126, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/opt/netbox/venv/lib/python3.8/site-packages/netbox_dns/migrations/0005_update_ns_records.py", line 24, in create_initial_ns_records
    Record.objects.update_or_create(
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/models/query.py", line 608, in update_or_create
    obj, created = self.select_for_update().get_or_create(defaults, **kwargs)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/models/query.py", line 588, in get_or_create
    return self.create(**params), True
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/models/query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "/opt/netbox/venv/lib/python3.8/site-packages/netbox_dns/models.py", line 542, in save
    zone = self.zone
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 187, in __get__
    rel_obj = self.get_object(instance)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 154, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/models/query.py", line 431, in get
    num = len(clone)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/models/query.py", line 262, in __len__
    self._fetch_all()
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column netbox_dns_zone.soa_serial_auto does not exist
LINE 1: ...e"."soa_expire", "netbox_dns_zone"."soa_minimum", "netbox_dn...
                                                             ^

**Comment by peteeckel** [comment]
I'm just trying to reproduce this. 

1. Installed a plain vanilla Netbox 3.10 in a new virtual environment and ran the migration.
2. Upgraded Netbox to 3.1.1 and updated requirements. Now I have the situation you described in your issue (3.1.1 with DB from 3.0.10).
3. Installed Netbox DNS 0.7 from PyPi and enabled it in configuration.py
4. Ran the migration.

```
(netbox) [root@dns netbox]# /opt/netbox/netbox/manage.py migrate 
Operations to perform:
  Apply all migrations: admin, auth, circuits, contenttypes, dcim, django_rq, extras, ipam, netbox_dns, sessions, social_django, taggit, tenancy, users, virtualization, wireless
Running migrations:
  Applying circuits.0003_extend_tag_support... OK
  Applying circuits.0004_rename_cable_peer... OK
  Applying tenancy.0003_contacts... OK
  Applying tenancy.0004_extend_tag_support... OK
  Applying ipam.0051_extend_tag_support... OK
  Applying extras.0063_webhook_conditions... OK
  Applying extras.0064_configrevision... OK
  Applying ipam.0052_fhrpgroup... OK
  Applying ipam.0053_asn_model... OK
  Applying dcim.0134_interface_wwn_bridge... OK
  Applying dcim.0135_tenancy_extensions... OK
  Applying dcim.0136_device_airflow... OK
  Applying dcim.0137_relax_uniqueness_constraints... OK
  Applying dcim.0138_extend_tag_support... OK
  Applying dcim.0139_rename_cable_peer... OK
  Applying wireless.0001_wireless... OK
  Applying dcim.0140_wireless... OK
  Applying dcim.0141_asn_model... OK
  Applying dcim.0142_rename_128gfc_qsfp28... OK
  Applying dcim.0143_remove_primary_for_related_name... OK
  Applying django_rq.0001_initial... OK
  Applying extras.0065_imageattachment_change_logging... OK
  Applying extras.0066_customfield_name_validation... OK
  Applying netbox_dns.0001_initial... OK
  Applying netbox_dns.0002_zone_default_ttl... OK
  Applying netbox_dns.0003_soa_managed_records... OK
  Applying netbox_dns.0004_create_ptr_for_a_aaaa_records... OK
  Applying netbox_dns.0005_update_ns_records... OK
  Applying netbox_dns.0006_zone_soa_serial_auto... OK
  Applying netbox_dns.0007_alter_zone_soa_serial_auto... OK
  Applying social_django.0001_initial... OK
  Applying social_django.0002_add_related_name... OK
  Applying social_django.0003_alter_email_max_length... OK
  Applying social_django.0004_auto_20160423_0400... OK
  Applying social_django.0005_auto_20160727_2333... OK
  Applying social_django.0006_partial... OK
  Applying social_django.0007_code_timestamp... OK
  Applying social_django.0008_partial_timestamp... OK
  Applying social_django.0009_auto_20191118_0520... OK
  Applying social_django.0010_uid_db_index... OK
  Applying virtualization.0024_cluster_relax_uniqueness... OK
  Applying virtualization.0025_extend_tag_support... OK
  Applying virtualization.0026_vminterface_bridge... OK
```

Unfortunately I can't reproduce your error, so I'm probably doing something differently. Can you please provide detailed steps to reproduce the problem so I can find what the culprit is?

**Comment by D1StrX** [comment]
Weird. Also because I have a brand new Netbox installation now, with imported db. 
![image](https://user-images.githubusercontent.com/40062371/146805801-c749d9b9-d112-4d1b-be1f-fcf89e4fddf5.png)
It just won't create the column. I could completely uninstall the plugin + database. But of course that isn't a nice solution when you have a lot of data in it.

**Ran the migration again:**
Operations to perform:
  Apply all migrations: admin, auth, circuits, contenttypes, dcim, django_rq, extras, ipam, netbox_dns, sessions, social_django, taggit, tenancy, users, virtualization, wireless
Running migrations:
  Applying netbox_dns.0005_update_ns_records...Traceback (most recent call last):
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/models/query.py", line 581, in get_or_create
    return self.get(**kwargs), False
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
netbox_dns.models.DoesNotExist: Record matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 173, in __get__
    rel_obj = self.field.get_cached_value(instance)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/models/fields/mixins.py", line 15, in get_cached_value
    return instance._state.fields_cache[cache_name]
KeyError: 'zone'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column netbox_dns_zone.soa_serial_auto does not exist
LINE 1: ...e"."soa_expire", "netbox_dns_zone"."soa_minimum", "netbox_dn...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/netbox/netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 244, in handle
    post_migrate_state = executor.migrate(
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/migrations/migration.py", line 126, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/opt/netbox/venv/lib/python3.8/site-packages/netbox_dns/migrations/0005_update_ns_records.py", line 24, in create_initial_ns_records
    Record.objects.update_or_create(
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/models/query.py", line 608, in update_or_create
    obj, created = self.select_for_update().get_or_create(defaults, **kwargs)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/models/query.py", line 588, in get_or_create
    return self.create(**params), True
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/models/query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "/opt/netbox/venv/lib/python3.8/site-packages/netbox_dns/models.py", line 542, in save
    zone = self.zone
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 187, in __get__
    rel_obj = self.get_object(instance)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 154, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/models/query.py", line 431, in get
    num = len(clone)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/models/query.py", line 262, in __len__
    self._fetch_all()
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column netbox_dns_zone.soa_serial_auto does not exist
LINE 1: ...e"."soa_expire", "netbox_dns_zone"."soa_minimum", "netbox_dn...
                                                             ^
Let me know if you have other suggestions ;)

**Comment by D1StrX** [comment]
Running PostgreSQL 12.9.
Found something when I clicked on _Manage Records_:
a new NetBox release, the upgrade script must
be run to apply any new database migrations. You can run migrations manually by executing
```
<code>python3 manage.py migrate</code> from the command line.
</p>
<p>
<i class="mdi mdi-alert"></i> <strong>Unsupported PostgreSQL version</strong> - Ensure that PostgreSQL version 9.6 or higher is in use. You
can check this by connecting to the database using NetBox's credentials and issuing a query for
<code>SELECT VERSION()</code>.
</p>

<hr />
<p>
The complete exception is provided below:
</p>
<pre class="block"><strong>&lt;class &#x27;django.db.utils.ProgrammingError&#x27;&gt;</strong><br />
column netbox_dns_zone.soa_serial_auto does not exist
LINE 1: ...e&quot;.&quot;soa_expire&quot;, &quot;netbox_dns_zone&quot;.&quot;soa_minimum&quot;, &quot;netbox_dn...
^


Python version: 3.8.10
NetBox version: 3.1.1</pre>
<p>
If further assistance is required, please post to the <a href="https://github.com/netbox-community/netbox/discussions">NetBox discussion forum</a> on GitHub.
</p>
<div class="text-end">
<a href="/" class="btn btn-primary">Home Page</a>
</div>
</div>
</div>
</div>
</div>
</div>
</body>

</html>
```

**Comment by peteeckel** [comment]
The fact that the column is not created is not the root cause of the problem. What's failing is migration 0005:

```
Applying netbox_dns.0005_update_ns_records...Traceback (most recent call last):
File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/models/query.py", line 581, in get_or_create
return self.get(**kwargs), False
File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/models/query.py", line 435, in get
raise self.model.DoesNotExist(
netbox_dns.models.DoesNotExist: Record matching query does not exist.
```

0005 does not create any column, it just updates the NS records for all zones (based on the SOA data and the NS entries in the zones). That seems to fail for some reason, and we need to find out why.

**Comment by peteeckel** [comment]
I think I have an idea what goes wrong. The problem is that you have zones with associated name servers in your database, and migration 0005 tries to insert records for the nameservers using the current model, which needs the soa_serial_auto field. Unfortunately though the migration that creates that field has not been run yet (that would be 0006), and so the operation in 0005 fails.

I can reproduce this in the Django shell:

```
>>> from netbox_dns.models import Zone, Record
>>> 
>>> for zone in Zone.objects.all():
...     nameservers = zone.nameservers.all()
...     nameserver_names = [f'{ns.name.rstrip(".")}.' for ns in nameservers]
...     delete_ns = zone.record_set.filter(type=Record.NS, managed=True).exclude(
...         value__in=nameserver_names
...     )
...     for ns in nameserver_names:
...         Record.objects.update_or_create(
...             zone_id=zone.pk,
...             type=Record.NS,
...             name=ns_name,
...             ttl=ns_ttl,
...             value=ns,
...             managed=True,
...         )
... 
Traceback (most recent call last):
  File "/opt/netbox/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column netbox_dns_zone.soa_serial_auto does not exist
LINE 1: ...e"."soa_expire", "netbox_dns_zone"."soa_minimum", "netbox_dn...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/opt/netbox/lib/python3.8/site-packages/django/db/models/query.py", line 280, in __iter__
    self._fetch_all()
  File "/opt/netbox/lib/python3.8/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/opt/netbox/lib/python3.8/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/opt/netbox/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/opt/netbox/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/netbox/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/netbox/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/netbox/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/netbox/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column netbox_dns_zone.soa_serial_auto does not exist
LINE 1: ...e"."soa_expire", "netbox_dns_zone"."soa_minimum", "netbox_dn...
```

It should be easy to fix, but I'd like to provide a workaround for you to get you running first. Please hang on.

**Comment by peteeckel** [comment]
OK, here we go.

Please find the migrations 0005 and 0006 (they should be in `/opt/netbox/venv/lib/python3.8/site-packages/`) and edit them like this:

```
diff --git a/netbox_dns/migrations/0005_update_ns_records.py b/netbox_dns/migrations/0005_update_ns_records.py
index 1f81ad7..42f7d14 100644
--- a/netbox_dns/migrations/0005_update_ns_records.py
+++ b/netbox_dns/migrations/0005_update_ns_records.py
@@ -34,7 +34,7 @@ def create_initial_ns_records(apps, schema_editor):
 class Migration(migrations.Migration):
 
     dependencies = [
-        ("netbox_dns", "0004_create_ptr_for_a_aaaa_records"),
+        ("netbox_dns", "0007_alter_zone_soa_serial_auto"),
     ]
 
     operations = [
diff --git a/netbox_dns/migrations/0006_zone_soa_serial_auto.py b/netbox_dns/migrations/0006_zone_soa_serial_auto.py
index aef58fd..9234c35 100644
--- a/netbox_dns/migrations/0006_zone_soa_serial_auto.py
+++ b/netbox_dns/migrations/0006_zone_soa_serial_auto.py
@@ -7,7 +7,7 @@ from django.db import migrations, models
 class Migration(migrations.Migration):
 
     dependencies = [
-        ("netbox_dns", "0005_update_ns_records"),
+        ("netbox_dns", "0004_create_ptr_for_a_aaaa_records")
     ]
 
     operations = [
```

This fixes the dependencies between the migrations so that 0005 gets executed after 0007. 

Then, run the migrations:

```
(netbox) [root@dns netbox]# /opt/netbox/netbox/manage.py migrate netbox_dns 0005
Operations to perform:
  Target specific migration: 0005_update_ns_records, from netbox_dns
Running migrations:
  Applying netbox_dns.0006_zone_soa_serial_auto... OK
  Applying netbox_dns.0007_alter_zone_soa_serial_auto... OK
  Applying netbox_dns.0005_update_ns_records... OK
```

That worked for me.

**Comment by D1StrX** [comment]
Not a git expert, but diff --git is:
`diff: unrecognized option '--git'`
what does give more output:
git diff a/netbox_dns/migrations/0005_update_ns_records.py b/netbox_dns/migrations/0005_update_ns_records.py
What should be filled for path `a` and path `b` ?

**Comment by peteeckel** [comment]
Sorry for confusing you with the git diff overhead - please edit the files manually, or would you rather have a patch file (manually is probably much quicker).

**Comment by D1StrX** [comment]
Amazing! Works perfect!
