### ISSUE TITLE
Tests failing in current main branch

### ISSUE THREAD

**Issue by peteeckel** [auroraresearchlab/netbox-dns#36]
While testing the changes for PR #35, I noticed that some of the tests for netbox_dns fail:

```
(netbox) [root@dns netbox-dns]# /opt/netbox/netbox/manage.py test netbox_dns
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
......................................F....F......................F....F......................F....F....
======================================================================
FAIL: test_get_object_anonymous (netbox_dns.tests.test_views.NameServerTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/netbox/lib/python3.8/site-packages/django/test/utils.py", line 387, in inner
    return func(*args, **kwargs)
  File "/opt/netbox/netbox/utilities/testing/views.py", line 62, in test_get_object_anonymous
    self.assertHttpStatus(response, 200)
  File "/opt/netbox/netbox/utilities/testing/base.py", line 68, in assertHttpStatus
    self.assertEqual(response.status_code, expected_status, err_message)
AssertionError: 302 != 200 : Expected HTTP status 200; received 302: No data

======================================================================
FAIL: test_list_objects_anonymous (netbox_dns.tests.test_views.NameServerTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/netbox/lib/python3.8/site-packages/django/test/utils.py", line 387, in inner
    return func(*args, **kwargs)
  File "/opt/netbox/netbox/utilities/testing/views.py", line 401, in test_list_objects_anonymous
    self.assertHttpStatus(response, 200)
  File "/opt/netbox/netbox/utilities/testing/base.py", line 68, in assertHttpStatus
    self.assertEqual(response.status_code, expected_status, err_message)
AssertionError: 302 != 200 : Expected HTTP status 200; received 302: No data

======================================================================
FAIL: test_get_object_anonymous (netbox_dns.tests.test_views.RecordTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/netbox/lib/python3.8/site-packages/django/test/utils.py", line 387, in inner
    return func(*args, **kwargs)
  File "/opt/netbox/netbox/utilities/testing/views.py", line 62, in test_get_object_anonymous
    self.assertHttpStatus(response, 200)
  File "/opt/netbox/netbox/utilities/testing/base.py", line 68, in assertHttpStatus
    self.assertEqual(response.status_code, expected_status, err_message)
AssertionError: 302 != 200 : Expected HTTP status 200; received 302: No data

======================================================================
FAIL: test_list_objects_anonymous (netbox_dns.tests.test_views.RecordTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/netbox/lib/python3.8/site-packages/django/test/utils.py", line 387, in inner
    return func(*args, **kwargs)
  File "/opt/netbox/netbox/utilities/testing/views.py", line 401, in test_list_objects_anonymous
    self.assertHttpStatus(response, 200)
  File "/opt/netbox/netbox/utilities/testing/base.py", line 68, in assertHttpStatus
    self.assertEqual(response.status_code, expected_status, err_message)
AssertionError: 302 != 200 : Expected HTTP status 200; received 302: No data

======================================================================
FAIL: test_get_object_anonymous (netbox_dns.tests.test_views.ZoneTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/netbox/lib/python3.8/site-packages/django/test/utils.py", line 387, in inner
    return func(*args, **kwargs)
  File "/opt/netbox/netbox/utilities/testing/views.py", line 62, in test_get_object_anonymous
    self.assertHttpStatus(response, 200)
  File "/opt/netbox/netbox/utilities/testing/base.py", line 68, in assertHttpStatus
    self.assertEqual(response.status_code, expected_status, err_message)
AssertionError: 302 != 200 : Expected HTTP status 200; received 302: No data

======================================================================
FAIL: test_list_objects_anonymous (netbox_dns.tests.test_views.ZoneTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/netbox/lib/python3.8/site-packages/django/test/utils.py", line 387, in inner
    return func(*args, **kwargs)
  File "/opt/netbox/netbox/utilities/testing/views.py", line 401, in test_list_objects_anonymous
    self.assertHttpStatus(response, 200)
  File "/opt/netbox/netbox/utilities/testing/base.py", line 68, in assertHttpStatus
    self.assertEqual(response.status_code, expected_status, err_message)
AssertionError: 302 != 200 : Expected HTTP status 200; received 302: No data

----------------------------------------------------------------------
Ran 104 tests in 5.102s

FAILED (failures=6)
Destroying test database for alias 'default'...
```

Unfortunately, it took me a while to find out that this was not due to my changes, but the tests also fail for the current main branch in exactly the same way. 

This seems to be because the Netbox ViewTestCases "GetObjectViewTestCase" and "ListObjectsViewTestCase" fail for anonymous access, possibly because the views return an HTTP response code 302 instead of 200 in this case. I haven't dug any deeper yet, but will investigate when I find the time.

**Comment by peteeckel** [comment]
Interesting question ... I get exactly the same results when I run the full test suite against netbox (currently on version 3.0.7) itself. So it doesn't seem to be an issue with netbox-dns after all. 

I also noticed that tests are **not** failing in the CI in Github. So there must be something done differently from just running `manage.py test`. But what?

```
======================================================================
FAIL: test_get_object_anonymous (circuits.tests.test_views.CircuitTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/netbox/lib/python3.8/site-packages/django/test/utils.py", line 387, in inner
    return func(*args, **kwargs)
  File "/vagrant/netbox/utilities/testing/views.py", line 68, in test_get_object_anonymous
    self.assertHttpStatus(response, 200)
  File "/vagrant/netbox/utilities/testing/base.py", line 68, in assertHttpStatus
    self.assertEqual(response.status_code, expected_status, err_message)
AssertionError: 302 != 200 : Expected HTTP status 200; received 302: No data

======================================================================
FAIL: test_list_objects_anonymous (circuits.tests.test_views.CircuitTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/netbox/lib/python3.8/site-packages/django/test/utils.py", line 387, in inner
    return func(*args, **kwargs)
  File "/vagrant/netbox/utilities/testing/views.py", line 407, in test_list_objects_anonymous
    self.assertHttpStatus(response, 200)
  File "/vagrant/netbox/utilities/testing/base.py", line 68, in assertHttpStatus
    self.assertEqual(response.status_code, expected_status, err_message)
AssertionError: 302 != 200 : Expected HTTP status 200; received 302: No data
```

**Comment by peteeckel** [comment]
I just opened an issue in netbox-community/netbox for this.

https://github.com/netbox-community/netbox/issues/7747
