### ISSUE TITLE
Migration fails with new Netbox version 3.1.0

### ISSUE THREAD

**Issue by peteeckel** [auroraresearchlab/netbox-dns#89]
It seems either the new Netbox version 3.1.0 or one of its prerequisites is incompatible with Netbox DNS. 

When trying to run `manage.py makemigrations` I get a long dump:
```
(netbox) [root@dns netbox]# /opt/netbox/netbox/manage.py makemigrations 
Traceback (most recent call last):
  File "/opt/netbox/netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/opt/netbox/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/netbox/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/netbox/lib/python3.8/site-packages/django/core/management/base.py", line 393, in execute
    self.check()
  File "/opt/netbox/lib/python3.8/site-packages/django/core/management/base.py", line 419, in check
    all_issues = checks.run_checks(
  File "/opt/netbox/lib/python3.8/site-packages/django/core/checks/registry.py", line 76, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/opt/netbox/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/opt/netbox/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/opt/netbox/lib/python3.8/site-packages/django/urls/resolvers.py", line 412, in check
    for pattern in self.url_patterns:
  File "/opt/netbox/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/netbox/lib/python3.8/site-packages/django/urls/resolvers.py", line 598, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/opt/netbox/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/netbox/lib/python3.8/site-packages/django/urls/resolvers.py", line 591, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/netbox/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/netbox/netbox/netbox/urls.py", line 9, in <module>
    from extras.plugins.urls import plugin_admin_patterns, plugin_patterns, plugin_api_patterns
  File "/opt/netbox/netbox/extras/plugins/urls.py", line 28, in <module>
    urlpatterns = import_object(f"{plugin_path}.urls.urlpatterns")
  File "/opt/netbox/netbox/extras/plugins/utils.py", line 31, in import_object
    spec.loader.exec_module(module)
  File "/opt/netbox/lib/python3.8/site-packages/netbox_dns/urls.py", line 5, in <module>
    from .views import (
  File "/opt/netbox/lib/python3.8/site-packages/netbox_dns/views.py", line 3, in <module>
    from netbox_dns.forms import (
  File "/opt/netbox/lib/python3.8/site-packages/netbox_dns/forms.py", line 37, in <module>
    class ZoneForm(BootstrapMixin, CustomFieldModelForm):
  File "/opt/netbox/lib/python3.8/site-packages/django/forms/models.py", line 226, in __new__
    new_class = super().__new__(mcs, name, bases, attrs)
  File "/opt/netbox/lib/python3.8/site-packages/django/forms/forms.py", line 31, in __new__
    new_class = super().__new__(mcs, name, bases, attrs)
  File "/opt/netbox/lib/python3.8/site-packages/django/forms/widgets.py", line 191, in __new__
    new_class = super().__new__(mcs, name, bases, attrs)
TypeError: Cannot create a consistent method resolution
order (MRO) for bases BootstrapMixin, CustomFieldModelForm
```

**Comment by peteeckel** [comment]
This also broke the tests for #88.

**Comment by hatsat32** [comment]
Wow, this is a huge issue. As you said we can limit the max version of netbox. I think `3.0.12` will be OK.

And we can fix the test workflow by adding `ref: 'v3.0.12'` in the `Checkout netbox` step.

For Netbox 3.1 we can investigate what the problem is later.

**Comment by peteeckel** [comment]
When I find the time today I'll try to bisect Netbox to find which commit caused the breakage - hoping that it actually **is** within Netbox itself and not in one of the new requirements 3.1 brings.

**Comment by hatsat32** [comment]
With PR #90 all tests passes for #88. Please see [Actions for PR 88](https://github.com/auroraresearchlab/netbox-dns/actions/runs/1553595310)

**Comment by peteeckel** [comment]
I just had a look at Netbox' code, and it certainly looks like you're correct in your assessment. 

While it won't be a big deal to fix Netbox DNS, I still think it's a pretty hefty change by the Netbox team, as it will break each and every plugin using the CustomField* classes. I'll open an issue with Netbox before starting any other action.

Thanks for looking into this!

**Comment by peteeckel** [comment]
Obviously the CustomField* classes are not a part of the public interface of Netbox, and using them is (as we can see) risky at best. 

I'll have a look into this. As far as I can see we aren't using custom fields at all, are we?

**Comment by DanSheps** [comment]
> Obviously the CustomField* classes are not a part of the public interface of Netbox, and using them is (as we can see) risky at best.

This is 100% correct.  Using internal API's (API's not documented as publically available) is sort of do at your own risk.

If you want to use internal API's, you are welcome to use the wrapper I developed for them (the plugin needs to be loaded as well).  Some internal API's don't have a wrapper but you are welcome to open an issue for it.  This won't guarantee there won't be an issue but it is at least 1 plugin that needs to be update versus various different codepoints in your plugin.

**Comment by peteeckel** [comment]
@DanSheps Thanks, that is definitely one way to handle it. Will your wrapper plugin also take care of changed paths in templates? In Netbox < 3.1, the "Tags" panel template was located in `extras/inc/tags_panel.html`, now it is in `inc/panels/tags.html`.

**Comment by peteeckel** [comment]
In general, the question is how much independence we can gain with regard to incompatibilities to different Netbox-versions.

On one hand, there is the option of relying on documented APIs as much as possible, which will require reimplementing lots of functionality and then trying to keep track of changes in Netbox to let the visual and functional differences not get too big. 

On the other hand there is the approach to just support the latest Netbox version as soon as it comes out and drop support for older versions immediately after incompatibilities surface. 

What I did with #92 is something in between - it retains compatibility with both Netbox 3.0.x and 3.1, and does not duplicate too much code already present in Netbox. But it isn't very pretty either.
